export const carData = [
  {
    name: "Jeep Renegade",
    img: "@/assets/bmw-m5.png",
    like: 74,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "SUV",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "BMW M2",
    like: 36,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Sedan",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "Ferarri Enzo",
    like: 85,
    seats: 2,
    luggage: 1,
    doors: 2,
    type: "Exotic Car",
    text: "Daily rate from",
    price: "167",
  },
  {
    name: "Ford Raptor",
    like: 59,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Truck",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "Mini Cooper",
    like: 74,
    seats: 19,
    luggage: 2,
    doors: 4,
    type: "Hatchback",
    text: "Daily rate from",
    price: "238",
  },
  {
    name: "VW Polo",
    like: 79,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Hatchback",
    text: "Daily rate from",
    price: "106",
  },
];