export const carData = [
  {
    name: "Jeep Renegade",
    img: '/images/jeep-renegade.png',
    like: 74,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "SUV",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "BMW M2",
    img: '/images/bmw-m5.png',
    like: 36,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Sedan",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "Ferarri Enzo",
    img: '/images/ferrari-enzo.png',
    like: 85,
    seats: 2,
    luggage: 1,
    doors: 2,
    type: "Exotic Car",
    text: "Daily rate from",
    price: "167",
  },
  {
    name: "Ford Raptor",
    img: '/images/ford-raptor.png',
    like: 59,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Truck",
    text: "Daily rate from",
    price: "244",
  },
  {
    name: "Mini Cooper",
    img: "/images/mini-cooper.png",
    like: 74,
    seats: 19,
    luggage: 2,
    doors: 4,
    type: "Hatchback",
    text: "Daily rate from",
    price: "238",
  },
  {
    name: "VW Polo",
    img: '/images/vw-polo.png',
    like: 79,
    seats: 5,
    luggage: 2,
    doors: 4,
    type: "Hatchback",
    text: "Daily rate from",
    price: "106",
  },
];

export const germanCities = [
  "Berlin", "Stuttgart", "Munich", "Hamburg", "Cologne", "Frankfurt", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hannover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mannheim", "Karlsruhe", "Augsburg", "Wiesbaden", "Mönchengladbach", "Gelsenkirchen", "Aachen", "Braunschweig", "Chemnitz", "Kiel", "Halle", "Magdeburg", "Freiburg im Breisgau", "Krefeld", "Mainz", "Lübeck", "Erfurt", "Oberhausen", "Rostock", "Kassel", "Hagen", "Potsdam", "Saarbrücken", "Hamm", "Ludwigshafen", "Mülheim", "Oldenburg", "Osnabrück", "Leverkusen", "Darmstadt", "Solingen", "Heidelberg", "Herne", "Neuss", "Regensburg", "Paderborn", "Ingolstadt", "Fürth", "Würzburg", "Ulm", "Heilbronn", "Pforzheim", "Wolfsburg", "Göttingen", "Bottrop", "Reutlingen", "Koblenz", "Bremerhaven", "Erlangen", "Recklinghausen", "Bergisch Gladbach", "Remscheid", "Jena", "Trier", "Salzgitter", "Moers", "Siegen", "Hildesheim", "Gütersloh", "Kaiserslautern", "Schwerin", "Esslingen", "Ludwigsburg", "Gladbeck", "Rosenheim", "Herten", "Hilden", "Elmshorn", "Halle-Neustadt", "Pinneberg", "Siegburg", "Germering", "Ostfildern", "Kornwestheim", "Unterschleißheim", "Hattersheim", "Unterhaching", "Weingarten", "Obertshausen", "Bad Soden am Taunus", "Haar", "Eschborn", "Ottobrunn", "Puchheim", "Gröbenzell", "Schenefeld", "Wolfratshausen", "Glinde", "Eilendorf", "Eppelheim", "Neubiberg", "Asperg", "Wentorf bei Hamburg", "Kronshagen", "Eichenau", "Steinbach am Taunus", "Weißenthurm", "Neulußheim", "Eichwalde", "Altbach", "Merzhausen", "Buckenhof", "Offenbach"
];

export const ordersData = [
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Completed",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Cancelled",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Scheduled",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Completed",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Cancelled",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Scheduled",
  // },
  // {
  //   id: 1245,
  //   car_name: "Jeep Renegade",
  //   pickup_location: "Lagos",
  //   dropoff_location: "Abuja",
  //   sightseeing: "Lagos",
  //   pickup_date: "10/10/2021",
  //   price: "244",
  //   status: "Completed",
  // },
  
];